config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"

  resources :aeds
  resources :monthly_inspections
end

app/models/aed.rb
class Aed < ApplicationRecord
  has_many :monthly_inspections, dependent: :destroy
  default_scope {order(name: :asc)}
end

app/models/aed_status_information.rb
class AedStatusInformation < ApplicationRecord
  belongs_to :monthly_inspections, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cabinet_status_information.rb
class CabinetStatusInformation < ApplicationRecord
  belongs_to :monthly_inspections, optional: true
end

app/models/monthly_inspection.rb
# frozen_string_literal: true

# Monthly Inspections are updated once a month with data about an AED
class MonthlyInspection < ApplicationRecord
  belongs_to :aed
  belongs_to :user

  has_one :cabinet_status_information, dependent: :destroy
  has_one :aed_status_information, dependent: :destroy

  accepts_nested_attributes_for :cabinet_status_information
  accepts_nested_attributes_for :aed_status_information

  enum cabinet_status: %i[not_applicable good damaged unable_to_check]
  enum aed_unit_status: %i[not_present out_of_service working needs_maintenance]
  enum rescue_kit_status: %i[present needs_attention]
end

app/models/officer_user.rb
class OfficerUser < User
  #code
end

app/models/supervisor_user.rb
class SupervisorUser < User
  #code
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :monthly_inspections
end

app/controllers/aeds_controller.rb
# frozen_string_literal: true

# AED is the main object used within this application
class AedsController < ApplicationController
  before_action :aed, except: %i[index new create]

  def index
    @aeds = Aed.all
  end

  def create
    if Aed.create!(aed_params)
      redirect_to aeds_path, notice: "AED was created."
    else
      redirect_to aeds_path, alert: "AED could not be created."
    end
  end

  def update
    if @aed.update(aed_params)
      redirect_to aeds_path, notice: "AED was updated."
    else
      redirect_to aeds_path, alert: "AED could not be updated."
    end
  end

  def destroy
    if @aed.destroy!
      redirect_to root_path, notice: "AED was deleted."
    else
      redirect_to root_path, alert: "AED could not be deleted."
    end
  end

private

  def aed
    @aed = Aed.find(params[:id])
  end

  def aed_params
    params.require(:aed).permit(
      :battery_expiration, :pad_1_expiration,
      :pad_2_expiration, :pediatric_pad_expiration,
      :date_of_purchase, :name, :model, :location,
      :serial_number
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/monthly_inspections_controller.rb
# frozen_string_literal: true

# Record Monthly Inspection Data for an AED
class MonthlyInspectionsController < ApplicationController
  before_action :cabinet_statuses, only: %i[new edit]
  before_action :aed_unit_statuses, only: %i[new edit]
  before_action :rescue_kit_statuses, only: %i[new edit]
  before_action :aeds, only: %i[new edit]

  def index
    respond_to do |format|
      format.html { @inspections = MonthlyInspection.all.order(year: :desc, month: :desc) }
      format.pdf do
        @reports = MonthlyInspection.where(year: params[:year], month: params[:month])
        render pdf:         "aed_inspection_#{params[:month]}_#{params[:year]}",
               disposition: "attachment",
               layout:      "pdf.html.erb",
               orientation: "landscape",
               template:    "monthly_inspections/show.pdf.erb",
               locals:      { reports: @reports }
      end
    end
  end

  def new
    @monthly_inspection = MonthlyInspection.new
    @monthly_inspection.build_cabinet_status_information
    @monthly_inspection.build_aed_status_information
  end

  def edit
    @monthly_inspection = MonthlyInspection.find(params[:id])
  end

  def show
    @monthly_inspection = MonthlyInspection.find(params[:id])
  end

  def create
    inspection = create_inspection(inspection_params)
    inspection.create_cabinet_status_information!(information: inspection_params[:cabinet_status_information_attributes][:information])
    inspection.create_aed_status_information!(information: inspection_params[:aed_status_information_attributes][:information])
    if inspection
      redirect_to monthly_inspections_path, notice: "Monthly Inspection was recorded."
    else
      redirect_to monthly_inspections_path, alert: "Monthly Inspection could not be saved."
    end
  end

  def update
    inspection = MonthlyInspection.find(params[:id])
    inspection.update(inspection_params)
    #inspection.update_cabinet_status_information!(information: inspection_params[:cabinet_status_information_attributes][:information])
    #inspection.update_aed_status_information!(information: inspection_params[:aed_status_information_attributes][:information])
    if inspection
      redirect_to monthly_inspections_path, notice: "Monthly Inspection was recorded."
    else
      redirect_to monthly_inspections_path, alert: "Monthly Inspection could not be saved."
    end
  end


private

  def inspection_params
    params.require(:monthly_inspection).permit(
      :year, :month, :aed_id, :cabinet_status,
      :aed_unit_status, :rescue_kit_status,
      :comments,
      cabinet_status_information_attributes: [:information],
      aed_status_information_attributes:     [:information]
    )
  end

  def inspection
    @monthly_inspection = MonthlyInspection.find(params[:id])
  end

  def aeds
    @aeds = Aed.all.map {|a| [a.name, a.id] }
  end

  def cabinet_statuses
    @cabinet_statuses = MonthlyInspection.cabinet_statuses.map {|s| [s[0].humanize, s[0]] }
  end

  def aed_unit_statuses
    @aed_unit_statuses = MonthlyInspection.aed_unit_statuses.map {|s| [s[0].humanize, s[0]] }
  end

  def rescue_kit_statuses
    @rescue_kit_statuses = MonthlyInspection.rescue_kit_statuses.map {|s| [s[0].humanize, s[0]] }
  end

  def create_inspection(inspection_params)
    MonthlyInspection.create!(
      month: inspection_params[:month], date: Date.today.day, comments: inspection_params[:comments],
      aed_id: inspection_params[:aed_id], cabinet_status: inspection_params[:cabinet_status],
      aed_unit_status: inspection_params[:aed_unit_status], user_id: current_user.id,
      rescue_kit_status: inspection_params[:rescue_kit_status], year: Date.today.year
    )
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# Static Pages
class PagesController < ApplicationController
  def index
    @months = MonthlyInspection.all.pluck(:year, :month).uniq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_format_helper.rb
module DataFormatHelper
  def format_date(date)
    if date
      date.strftime("%D")
    else
      ""
    end
  end
end

app/views/aeds/edit.html.erb
<div>
  <%= form_for @aed do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :location %>
      <%= f.text_field :location %>
    </div>
    <div class="field">
      <%= f.label :serial_number %>
      <%= @aed.serial_number %>
    </div>
    <div class="field">
      <%= f.label :model %>
      <%= @aed.model %>
    </div>
    <div class="field">
      <%= f.label :date_of_purchase %>
      <%= format_date(@aed.date_of_purchase) %>
    </div>
    <div class="field">
      <%= f.label :battery_expiration %>
      <%= f.date_field :battery_expiration %>
    </div>
    <div class="field">
      <%= f.label :pad_1_expiration %>
      <%= f.date_field :pad_1_expiration %>
    </div>
    <div class="field">
      <%= f.label :pad_2_expiration %>
      <%= f.date_field :pad_2_expiration %>
    </div>
    <div class="field">
      <%= f.label :pediatric_pad_expiration %>
      <%= f.date_field :pediatric_pad_expiration %>
    </div>
    <div>
      <%= link_to "Cancel", aeds_path, class: "cancel-link" %>
      <%= f.submit "Save", class: "button" %>
    </div>
  <% end %>
</div>

app/views/aeds/index.html.erb
<div class="field">
  <%= link_to "Add New AED", new_aed_path, class: "button" %>
</div>
<div>
  <table>
    <thead>
      <th>AED</th>
      <th>Location</th>
      <th>Pad 1 Expiration</th>
      <th>Pad 2 Expiration</th>
      <th>Pediatric Pad Expiration</th>
      <th>Battery Expiration</th>
      <th></th>
      <th></th>
    </thead>
    <tbody>
      <% @aeds.each do |aed| %>
        <tr>
          <td><%= aed.name %></td>
          <td><%= aed.location %></td>
          <td><%= format_date(aed.pad_1_expiration) %></td>
          <td><%= format_date(aed.pad_2_expiration) %></td>
          <td><%= format_date(aed.pediatric_pad_expiration) %></td>
          <td><%= format_date(aed.battery_expiration) %></td>
          <td><%= link_to "Edit", edit_aed_path(aed.id) %></td>
          <td><%= link_to "Delete", aed_path(aed.id), method: :delete, confirm: "Are you sure?" %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/aeds/new.html.erb
<div>
  <%= form_for :aed, url: aeds_path do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :location %>
      <%= f.text_field :location %>
    </div>
    <div class="field">
      <%= f.label :serial_number %>
      <%= f.text_field :serial_number %>
    </div>
    <div class="field">
      <%= f.label :model %>
      <%= f.text_field :model %>
    </div>
    <div class="field">
      <%= f.label :date_of_purchase %>
      <%= f.date_field :date_of_purchase %>
    </div>
    <div class="field">
      <%= f.label :battery_expiration %>
      <%= f.date_field :battery_expiration %>
    </div>
    <div class="field">
      <%= f.label :pad_1_expiration %>
      <%= f.date_field :pad_1_expiration %>
    </div>
    <div class="field">
      <%= f.label :pad_2_expiration %>
      <%= f.date_field :pad_2_expiration %>
    </div>
    <div class="field">
      <%= f.label :pediatric_pad_expiration %>
      <%= f.date_field :pediatric_pad_expiration %>
    </div>
    <div>
      <%= link_to "Cancel", aeds_path, class: "cancel-link" %>
      <%= f.submit "Save", class: "button" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AedInspections</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <%= render partial: "layouts/shared/header" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AedInspections</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_header.html.erb
<header>
  <nav>
    <%= link_to "Home", root_path %>
    <%= link_to "AEDs", aeds_path %>
    <%= link_to "Monthly Inspections", monthly_inspections_path %>
    <% if user_signed_in? %>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
    <% else %>
      <%= link_to('Login', new_user_session_path)  %>
    <% end %>
  </nav>
</header>

app/views/monthly_inspections/edit.html.erb
<div>
  <%= form_for @monthly_inspection do |f| %>
    <div class="field">
      <%= f.label :year %>
      <%= f.number_field :year %>
    </div>
    <div class="field">
      <%= f.label :month %>
      <%= f.number_field :month %>
    </div>
    <div class="field">
      <%= f.label :aed_id, "AED" %>
      <%= f.select :aed_id, @aeds %>
    </div>
    <div class="field">
      <%= f.label :cabinet_status %>
      <%= f.select :cabinet_status, @cabinet_statuses %>
    </div>
    <%= f.fields_for :cabinet_status_information, @monthly_inspection.cabinet_status_information do |form| %>
      <div class="field">
        <%= form.label :information, "Cabinet Information" %>
        <%= form.text_area :information %>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :aed_unit_status %>
      <%= f.select :aed_unit_status, @aed_unit_statuses %>
    </div>
    <%= f.fields_for :aed_status_information, @monthly_inspection.aed_status_information do |form| %>
      <div class="field">
        <%= form.label :information, "AED Information" %>
        <%= form.text_area :information %>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :rescue_kit_status %>
      <%= f.select :rescue_kit_status, @rescue_kit_statuses %>
    </div>
    <div class="field">
      <%= f.label :comments %>
      <%= f.text_area :comments %>
    </div>
    <div class="actions">
      <%= link_to "Cancel", monthly_inspections_path, class: "cancel-link" %>
      <%= f.submit "Save", class: "button" %>
    </div>
  <% end %>
</div>

app/views/monthly_inspections/index.html.erb
<div class="field">
  <%= link_to "New Inspection", new_monthly_inspection_path, class: "button" %>
</div>
<div>
  <table>
    <thead>
      <th>Month</th>
      <th>AED</th>
      <th>Cabinet Status</th>
      <th>Unit Status</th>
      <th>Rescue Kit Status</th>
      <th>Initials</th>
      <th></th>
      <th></th>
    </thead>
    <tbody>
      <% @inspections.each do |inspection| %>
        <tr>
          <td><%= inspection.month %>/<%= inspection.year %></td>
          <td><%= inspection.aed.name %></td>
          <td><%= inspection.cabinet_status.humanize %></td>
          <td><%= inspection.aed_unit_status.humanize %></td>
          <td><%= inspection.rescue_kit_status.humanize %></td>
          <td><%= inspection.user.initials %></td>
          <td><%= link_to "View", monthly_inspection_path(inspection.id) %></td>
          <td><%= link_to "Edit", edit_monthly_inspection_path(inspection.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/monthly_inspections/new.html.erb
<div>
  <%= form_for @monthly_inspection, url: monthly_inspections_path do |f| %>
    <div class="field">
      <%= f.label :year %>
      <%= f.number_field :year, value: Date.today.year, disabled: true %>
    </div>
    <div class="field">
      <%= f.label :month %>
      <%= f.number_field :month, value: Date.today.month %>
    </div>
    <div class="field">
      <%= f.label :aed_id, "AED" %>
      <%= f.select :aed_id, @aeds %>
    </div>
    <div class="field">
      <%= f.label :cabinet_status %>
      <%= f.select :cabinet_status, @cabinet_statuses %>
    </div>
    <%= f.fields_for :cabinet_status_information, @monthly_inspection.cabinet_status_information do |form| %>
      <div class="field">
        <%= form.label :information, "Cabinet Information" %>
        <%= form.text_area :information %>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :aed_unit_status %>
      <%= f.select :aed_unit_status, @aed_unit_statuses %>
    </div>
    <%= f.fields_for :aed_status_information, @monthly_inspection.aed_status_information do |form| %>
      <div class="field">
        <%= form.label :information, "AED Information" %>
        <%= form.text_area :information %>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :rescue_kit_status %>
      <%= f.select :rescue_kit_status, @rescue_kit_statuses %>
    </div>
    <div class="field">
      <%= f.label :comments %>
      <%= f.text_area :comments %>
    </div>
    <div class="actions">
      <%= link_to "Cancel", monthly_inspections_path, class: "cancel-link" %>
      <%= f.submit "Save", class: "button" %>
    </div>
  <% end %>
</div>

app/views/monthly_inspections/show.html.erb
<div>
  <div class="field">
    <strong>AED</strong>: <%= @monthly_inspection.aed.name %>
  </div>
  <div class="field">
    <strong>Inspection Date</strong>: <%= @monthly_inspection.created_at.in_time_zone.strftime("%d/%m/%y %H:%m") %>
  </div>
  <div class="field">
    <strong>Cabinet Status</strong>: <%= @monthly_inspection.cabinet_status.humanize %>
  </div>
  <div class="field">
    <strong>Cabinet Comments</strong>: <%= @monthly_inspection.cabinet_status_information.information %>
  </div>
  <div class="field">
    <strong>AED Unit Status</strong>: <%= @monthly_inspection.aed_unit_status.humanize %>
  </div>
  <div class="field">
    <strong>AED Unit Comments</strong>: <%= @monthly_inspection.aed_status_information.information %>
  </div>
  <div class="field">
    <strong>Rescue Kit Status</strong>: <%= @monthly_inspection.rescue_kit_status.humanize %>
  </div>
  <div class="field">
    <strong>Comments</strong>: <%= @monthly_inspection.comments %>
  </div>
  <div class="field">
    <strong>Inspected By</strong>: <%= @monthly_inspection.user.initials %>
  </div>
  <div class="field">
    <%= link_to "Back", monthly_inspections_path %>
  </div>
</div>

app/views/monthly_inspections/show.pdf.erb
<style>
  table {
    padding: 10px;
    border-spacing: 0;
    margin: auto;
    width: 100%;
    overflow: scroll;
  }

  thead {
    background-color: #3E606F;
    color: #FCFFF5;
  }

  th {
    padding: 20px;
  }

  tr:nth-child(even) {background-color: #f2f2f2;}

  td {
    text-align: center;
    padding: 20px;
  }

  a {
    text-decoration: none;
    color: #193441;

    &:hover {
      text-decoration: underline;
  }

</style>
<table>
  <thead>
    <th>Month</th>
    <th>AED</th>
    <th>Cabinet Status</th>
    <th>Cabinet Notes</th>
    <th>Unit Status</th>
    <th>Unit Notes</th>
    <th>Rescue Kit Status</th>
    <th>Initials</th>
  </thead>
  <tbody>
    <% @reports.each do |inspection| %>
      <tr>
        <td><%= inspection.created_at.in_time_zone.strftime("%d/%m/%Y %H:%m") %></td>
        <td><%= inspection.aed.name %></td>
        <td><%= inspection.cabinet_status.humanize %></td>
        <td><%= inspection.cabinet_status_information.information %></td>
        <td><%= inspection.aed_unit_status.humanize %></td>
        <td><%= inspection.aed_status_information.information %></td>
        <td><%= inspection.rescue_kit_status.humanize %></td>
        <td><%= inspection.user.initials %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/index.html.erb
<div class="field">
  <h3>Download Monthly Inspections</h3>
  <% @months.each do |report| %>
  <div class="field">
    <%= link_to monthly_inspections_path(year: report[0], month: report[1], format: :pdf), class: "button" do %>
      <%= Date::MONTHNAMES[report[1]] %> <%= report[0] %>
    <% end %>
  </div>
  <% end %>
</div>